name: Build Docs
inputs:
  inputs:
    extra-config:
      required: false
      type: string
    target-folder:
      require: false
      type: string

runs:
  using: composite
  steps:
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Configure
      shell: bash
      run:
        REPO_NAME=$(jq -r ".repository.name" "$GITHUB_EVENT_PATH")

        # avoid look up of API as it doesn't work from within actions without exposing the GITHUB_TOKEN here which is a security risk
        cat <<EOF >> docs/_config.yml
        repository_nwo: ${GITHUB_REPOSITORY}
        EOF

        if [[ -n "${INPUTS_TARGET-FOLDER}" ]]
        then
          echo "baseurl: /${REPO_NAME}/${INPUTS_TARGET-FOLDER}" >> docs/_config.yml
        fi

        # allow override of everything
        cat <<EOF >> docs/_config.yml
        ${EXTRA_CONFIG}
        EOF


    - name: Install and Build
      shell: bash
      run: |
        # TODO find a way for jekyll to perform this automatically
        convert docs/_assets/images/logo.png -define icon:auto-resize=256,64,48,32,16 docs/favicon.ico

        BUNDLE_GEMFILE=./docs/Gemfile bundle install
        BUNDLE_GEMFILE=./docs/Gemfile bundle exec jekyll build --source docs/ --destination build
